# Generated by Django 4.0.3 on 2022-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahalla',
            name='section',
            field=models.CharField(choices=[('I', '1-sektor'), ('II', '2-sektor'), ('III', '3-sektor'), ('IV', '4-sektor')], default='I', max_length=128),
        ),
    ]
